variable "do_region" {}
variable "do_spaces_access_id" {}
variable "cluster_name" {}
variable "cluster_version" {}
variable "cluster_tags" {}
variable "cluster_default_node_size" {}
variable "cluster_default_node_count" {}
variable "cluster_default_node_tags" {}
variable "kubeconfig_path" {}